version: "3.8"

networks:
  trial1:

services: 
    nginx:
      image: nginx:stable-alpine
      container_name: nginx
      ports:
        - "8000:80"
      volumes:
        - ./:/var/www/
        - ./default.conf:/etc/nginx/conf.d/default.conf
      networks: 
        - trial1
    
    app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: app
      working_dir: /var/www/
      volumes:
        - ./:/var/www/
      networks: 
        - trial1

    mysql:
      image: mysql:8.0
      container_name: mysql
      ports:
        - "3307:3306"
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      volumes:
        - mysqldata:/var/lib/mysql/
        - ./:/var/lib/mysql/
      networks: 
        - trial1


volumes: 
  mysqldata:


